server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json,application/xml,application/javascript
    min-response-size: 2048
  port: 8066

flashtsdb:
  config:
    tablename: flashtsdb
    accuracy: 0.1

hbase:
  config:
    hbase.zookeeper.quorum: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181

spring:
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  redis:
    password: dpp123456+_)
    host: redis-host
    port: 6379
    database: 10
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

